//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.IEC62056_21.AddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.IEC62056_21.AddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressTxt {
            get {
                return ResourceManager.GetString("AddressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Device Mode must be selected..
        /// </summary>
        internal static string DeviceModeSelectErrTxt {
            get {
                return ResourceManager.GetString("DeviceModeSelectErrTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Mode.
        /// </summary>
        internal static string DeviceModeTxt {
            get {
                return ResourceManager.GetString("DeviceModeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property Read Mode must be selected..
        /// </summary>
        internal static string PropertyReadModeSelectErrTxt {
            get {
                return ResourceManager.GetString("PropertyReadModeSelectErrTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property Write Mode must be selected..
        /// </summary>
        internal static string PropertyWriteModeSelectErrTxt {
            get {
                return ResourceManager.GetString("PropertyWriteModeSelectErrTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Table Read Mode must be selected..
        /// </summary>
        internal static string TableReadModeSelectErrTxt {
            get {
                return ResourceManager.GetString("TableReadModeSelectErrTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeTxt {
            get {
                return ResourceManager.GetString("TypeTxt", resourceCulture);
            }
        }
    }
}
